### ISSUE TITLE
Railcraft rails unobtainable

### ISSUE THREAD

**Issue by LudumSi** [ArchitektRadim/ArchitPack-Greg#1]
You have disabled the "track kit" option in the railcraft config. This makes it much harder to do anything with rails, and makes railcraft basically useless for it's main premise. As it is, it is not possible to craft the various junctions and other rails which make railcraft useful. 

If this is an intentional balance change, then you should probably also remove the track parts and the iron and steel spike mauls, as these are used for that system.

**Comment by ArchitektRadim** [comment]
I am sorry for the huge delay. Thanks a lot for the issue report, will take a look on it. It should be fixed in the next update released soon hopefully.

**Comment by ArchitektRadim** [comment]
Fixed in update 1.3.3
